plugins { id 'com.android.application' }

android {
    namespace 'com.shikanon.socks5proxy'
    compileSdk 35
    ndkVersion '27.2.12479018'
    defaultConfig {
        applicationId 'com.shikanon.socks5proxy'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '0.1.0'
        ndk { abiFilters 'arm64-v8a', 'armeabi-v7a', 'x86_64' }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildTypes {
        release { minifyEnabled false }
    }
}

dependencies {
    implementation files('libs/tunnelcore.aar')
}
