#!/usr/bin/env python3
"""Linux black-box FD regression. Only child processes receive a low rlimit."""
import argparse
import concurrent.futures
import contextlib
import json
import os
import resource
import signal
import socket
import socketserver
import subprocess
import tempfile
import time


def unused_address():
    with socket.socket() as sock:
        sock.bind(("127.0.0.1", 0))
        return sock.getsockname()


def address(value):
    return "%s:%d" % value


def fd_count(process):
    if process.poll() is not None:
        raise AssertionError("proxy exited early: %s" % process.returncode)
    return len(os.listdir("/proc/%d/fd" % process.pid))


def eventually(predicate, timeout=5):
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if predicate():
            return
        time.sleep(0.02)
    raise AssertionError("condition not reached before timeout")


def read_full(sock, size):
    data = b""
    while len(data) < size:
        part = sock.recv(size - len(data))
        if not part:
            raise AssertionError("unexpected EOF")
        data += part
    return data


def start(binary, arguments, limit, log):
    def set_limit():
        resource.setrlimit(resource.RLIMIT_NOFILE, (limit, limit))
    process = subprocess.Popen([binary] + arguments, stdout=log, stderr=log, preexec_fn=set_limit)
    return process


def ready(process, target):
    def check():
        fd_count(process)
        try:
            with socket.create_connection(target, timeout=0.2):
                return True
        except OSError:
            return False
    eventually(check)
    time.sleep(0.2)


def stop(process):
    if process.poll() is None:
        process.send_signal(signal.SIGTERM)
        try:
            process.wait(timeout=3)
        except subprocess.TimeoutExpired:
            process.kill()
            process.wait()
            raise AssertionError("proxy did not shut down after SIGTERM")


class Echo(socketserver.BaseRequestHandler):
    def handle(self):
        self.request.settimeout(3)
        data = bytearray()
        while True:
            chunk = self.request.recv(8192)
            if not chunk:
                break
            data.extend(chunk)
        self.request.sendall(b"reply:" + data)


class EchoServer(socketserver.ThreadingTCPServer):
    # The test origin must accept the load generated by the proxy; the standard
    # server's default backlog of five is smaller than our sixteen workers.
    request_queue_size = 128
    daemon_threads = True


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--client", required=True)
    parser.add_argument("--server", required=True)
    parser.add_argument("--limit", type=int, default=64)
    parser.add_argument("--sessions", type=int, default=16)
    parser.add_argument("--iterations", type=int, default=400)
    parser.add_argument("--legacy", action="store_true", help="Run the upstream refusal probe without new CLI flags")
    args = parser.parse_args()
    if not os.path.isdir("/proc/self/fd"):
        parser.error("requires Linux /proc")
    if args.limit < 32 or not 1 <= args.sessions <= (args.limit - 16) // 2:
        parser.error("reserve 16 FDs and budget two FDs per session")
    password = "resource-test"
    common = ["-passwd", password, "-type", "random"]
    if not args.legacy:
        common += ["-max-connections", str(args.sessions), "-dial-timeout", "300ms",
                   "-handshake-timeout", "300ms", "-idle-timeout", "300ms"]
    report = {"rlimit_nofile": args.limit, "max_connections": args.sessions, "iterations": args.iterations}
    processes = []
    with tempfile.TemporaryFile(mode="w+") as log:
        try:
            absent, local = unused_address(), unused_address()
            client = start(args.client, common + ["-local", address(local), "-server", address(absent), "-recv", "socks5"], args.limit, log)
            processes.append(client)
            ready(client, local)
            baseline = fd_count(client)
            peak = baseline
            held = []
            try:
                for _ in range(min(args.iterations, args.limit - 16)):
                    held.append(socket.create_connection(local, timeout=1))
                    time.sleep(0.002)
                    peak = max(peak, fd_count(client))
                time.sleep(0.2)
                retained = fd_count(client)
                report["upstream_refusal"] = {"before": baseline, "peak": peak, "after_held_peers": retained}
                # Peer sockets deliberately remain open: GC and remote closure
                # must not be needed to clean up a failed upstream dial.
                assert retained <= baseline + 4, report
                for sock in held:
                    sock.settimeout(1)
                    assert sock.recv(1) == b"", "failed dial left local socket open"
            finally:
                for sock in held:
                    sock.close()
            for _ in range(args.iterations):
                with socket.create_connection(local, timeout=1) as sock:
                    sock.settimeout(1)
                    assert sock.recv(1) == b""
            eventually(lambda: fd_count(client) <= baseline + 2)
            report["upstream_refusal"]["after"] = fd_count(client)
            stop(client)
            if args.legacy:
                return
            server_address, local = unused_address(), unused_address()
            server = start(args.server, common + ["-local", address(server_address)], args.limit, log)
            processes.append(server)
            ready(server, server_address)
            client = start(args.client, common + ["-local", address(local), "-server", address(server_address), "-recv", "socks5"], args.limit, log)
            processes.append(client)
            ready(client, local)
            baselines = [fd_count(client), fd_count(server)]
            # Flood incomplete handshakes beyond admission capacity.
            peers = [socket.create_connection(local, timeout=1) for _ in range(args.sessions * 3)]
            time.sleep(0.1)
            peaks = [fd_count(client), fd_count(server)]
            assert all(p <= b + args.sessions * 2 + 4 for p, b in zip(peaks, baselines)), peaks
            for peer in peers:
                peer.close()
            eventually(lambda: all(fd_count(p) <= b + 4 for p, b in zip([client, server], baselines)))
            report["incomplete_handshakes"] = {"before": baselines, "peak": peaks, "after": [fd_count(client), fd_count(server)]}

            with EchoServer(("127.0.0.1", 0), Echo) as echo:
                import threading
                worker = threading.Thread(target=echo.serve_forever, daemon=True)
                worker.start()
                port = echo.server_address[1]
                def exchange(_):
                    with socket.create_connection(local, timeout=3) as sock:
                        sock.settimeout(3)
                        # Pipelined greeting, request and payload.
                        sock.sendall(bytes([5, 1, 0, 5, 1, 0, 1, 127, 0, 0, 1, port >> 8, port & 255]) + b"payload")
                        assert read_full(sock, 2) == b"\x05\x00"
                        assert read_full(sock, 10)[1] == 0
                        sock.shutdown(socket.SHUT_WR)
                        assert read_full(sock, 13) == b"reply:payload"
                        assert sock.recv(1) == b""
                try:
                    with concurrent.futures.ThreadPoolExecutor(max_workers=args.sessions) as pool:
                        list(pool.map(exchange, range(args.iterations)))
                finally:
                    echo.shutdown()
                    worker.join()
            eventually(lambda: all(fd_count(p) <= b + 4 for p, b in zip([client, server], baselines)))
            report["short_connections"] = {"before": baselines, "after": [fd_count(client), fd_count(server)]}
            # Verify bounded shutdown while sessions are waiting for bytes.
            with contextlib.ExitStack() as stack:
                for _ in range(args.sessions):
                    stack.enter_context(socket.create_connection(local, timeout=1))
                stop(client)
                stop(server)
            assert client.returncode == server.returncode == 0
            report["shutdown"] = "clean"
        except Exception:
            log.seek(0)
            report["log_tail"] = log.read()[-3000:]
            raise
        finally:
            for process in processes:
                stop(process)
            print(json.dumps(report, indent=2), flush=True)


if __name__ == "__main__":
    main()
